### ISSUE TITLE
Finalist/Eliminated players are displayed under spectating players

### ISSUE THREAD

**Issue by KemTM** [BossBravo/Trackmania2020_LastManStandingCup#9]
**Describe the bug**
Finalist and eliminated players are sorted below spectators with 0 points

**To Reproduce**
1. Have some spectators on the server
2. Start the match
3. Get into finalist mode
4. Find your finalist below spectators

**Expected behavior**
Finalists should be sorted above spectators

**Screenshots**
![image](https://user-images.githubusercontent.com/7620234/133939119-b7b31c5d-3f87-41db-b340-bef6940537f7.png)

**Comment by BossBravo** [comment]
Done in https://github.com/BossBravo/Trackmania2020_LastManStandingCup/commit/200bc66b03dac800860c86020dbf3604271844bc
Spectators will now be displayed in a different color and on the bottom of the score table.
